// <auto-generated />
using Integrate.Interview.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Integrate.Interview.Api.Database.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Integrate.Interview.Api.Database.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zipcode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Birmingham",
                            FirstName = "Hunter",
                            LastName = "Horton",
                            State = "Alabama",
                            StreetAddress = "123 Mockingbird Lane",
                            Title = "Mr",
                            Zipcode = "35242"
                        },
                        new
                        {
                            Id = 2,
                            City = "Birmingham",
                            FirstName = "Aaron",
                            LastName = "Hall",
                            State = "Alabama",
                            StreetAddress = "777 Sunshine Drive",
                            Title = "Mr",
                            Zipcode = "35242"
                        },
                        new
                        {
                            Id = 3,
                            City = "Birmingham",
                            FirstName = "Robert",
                            LastName = "Blackwood",
                            State = "Alabama",
                            StreetAddress = "1 Pleasant Way",
                            Title = "Mr",
                            Zipcode = "35242"
                        },
                        new
                        {
                            Id = 4,
                            City = "Birmingham",
                            FirstName = "Scott",
                            LastName = "Carl",
                            State = "Alabama",
                            StreetAddress = "246 Yellowhammer Circle",
                            Title = "Mr",
                            Zipcode = "35242"
                        },
                        new
                        {
                            Id = 5,
                            City = "Birmingham",
                            FirstName = "Andrew",
                            LastName = "Pearson",
                            State = "Alabama",
                            StreetAddress = "357 Oriole Parkway",
                            Title = "Mr",
                            Zipcode = "35242"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
